#!/bin/sh

#if [ ! -f build-tc.rb ]; then
#	echo "$0: No 'build-tc.rb' script found. Run this from a directory with a valid 'build-tc.rb' script."
#fi

if [ "x${JAVA_HOME}" = "x" ]; then
	JAVA_HOME=${TC_JAVA_HOME_15}
	export JAVA_HOME
fi

JRUBY_HOME=`dirname $0`/../../buildsystems/jruby
export JRUBY_HOME

if [ ! -d "${JRUBY_HOME}" ]; then
	echo "--------------------------------------------------------------------------------"
	echo "LOADING JRUBY USING IVY"
	echo ""
	$ANT_HOME/bin/ant -buildfile `dirname $0`/buildconfig/build.xml
fi


	echo ""
	echo "--------------------------------------------------------------------------------"
	echo "RUNNING TCBUILD"
	echo ""
	exec /bin/sh $JRUBY_HOME/bin/jruby -Ibuildscripts buildscripts/build-tc.rb "$@"
