#!/bin/sh

if test -z "${JAVA_HOME}"; then
	echo "JAVA_HOME is not set"
  exit 1
fi

if test -z "${ANT_HOME}"; then
	echo "ANT_HOME is not set"
  exit 1
fi

build_system_dir=`dirname $0`/../../buildsystems

JRUBY_HOME="$build_system_dir/jruby-1.1.2-20090208"
export JRUBY_HOME

if test ! -d "${JRUBY_HOME}"; then
	echo "--------------------------------------------------------------------------------"
	echo "LOADING JRUBY USING IVY"
	echo ""
	"${ANT_HOME}/bin/ant" -buildfile "$build_system_dir/install-jruby-build.xml"
fi

echo ""
echo "--------------------------------------------------------------------------------"
echo "RUNNING TCBUILD"
echo ""
exec /bin/bash "${JRUBY_HOME}/bin/jruby" -Ibuildscripts buildscripts/build-tc.rb "$@"
