<DOCFLEX_TEMPLATE VER='1.7'>
CREATED='2005-04-26 03:31:00'
LAST_UPDATE='2006-10-09 06:34:50'
DESIGNER_TOOL='DocFlex SDK 1.0'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='xsddoc'
ROOT_ETS={'xs:%element';'xs:attribute';'xs:attributeGroup';'xs:complexType'}
<TEMPLATE_PARAMS>
	PARAM={
		param.name='name';
		param.type='string';
		param.string.default='..';
	}
	PARAM={
		param.name='qualifiedName';
		param.type='string';
	}
	PARAM={
		param.name='fmt.allowNestedTables';
		param.displayName='Allow nested tables';
		param.type='boolean';
		param.boolean.default='true';
	}
</TEMPLATE_PARAMS>
FMT={
	doc.lengthUnits='pt';
	doc.hlink.style.link='cs7';
}
<STYLES>
	CHAR_STYLE={
		style.name='Attribute Name';
		style.id='cs1';
		text.font.name='Courier New';
		text.font.size='8';
		text.color.foreground='#990000';
	}
	CHAR_STYLE={
		style.name='Code';
		style.id='cs2';
		text.font.name='Courier New';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Code Smaller';
		style.id='cs3';
		text.font.name='Courier New';
		text.font.size='8';
	}
	CHAR_STYLE={
		style.name='Code Smallest';
		style.id='cs4';
		text.font.name='Courier New';
		text.font.size='7.5';
	}
	CHAR_STYLE={
		style.name='Content Model';
		style.id='cs5';
		text.font.name='Verdana';
		text.font.size='8.5';
	}
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs6';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs7';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Inset Heading';
		style.id='s1';
		text.font.style.bold='true';
		text.color.foreground='#990000';
		par.margin.bottom='6.8';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s2';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Underline';
		style.id='cs8';
		text.decor.underline='true';
	}
	CHAR_STYLE={
		style.name='XML Markup';
		style.id='cs9';
		text.color.foreground='#0000FF';
		text.option.nbsps='true';
	}
	CHAR_STYLE={
		style.name='XML Name';
		style.id='cs10';
		text.color.foreground='#990000';
	}
	CHAR_STYLE={
		style.name='XML Source';
		style.id='cs11';
		text.font.name='Verdana';
		text.font.size='8';
	}
</STYLES>
<ROOT>
	<ELEMENT_ITER>
		DESCR='case of element'
		MATCHING_ET='xs:%element'
		TARGET_ETS={'#STUB';'xs:%complexType';'xs:%simpleType'}
		SCOPE='advanced-location-rules'
		RULES={
			{'*','{(type = getAttrStringValue("type")) != "" ? \n{ \n  qName = QName (type);\n  ((el = findElementByKey ("types", qName)) == null && isXSPredefinedType (qName)) ?\n  {\n    el = StubXMLElement();\n    el.setXMLAttribute("name", type);\n  };\n  Enum (el)\n}}::(#STUB|xs:complexType|xs:simpleType)'};
			{'*','(xs:complexType|xs:simpleType)'};
		}
		<BODY>
			<SS_CALL>
				MATCHING_ET='xs:%complexType'
				SS_NAME='Element Rep (complexType)'
				PARAMS_EXPR='Array (getParam("qualifiedName"))'
			</SS_CALL>
			<SS_CALL>
				MATCHING_ETS={'#STUB';'xs:%simpleType'}
				SS_NAME='Element Rep (simpleType)'
				PARAMS_EXPR='Array (getParam("qualifiedName"))'
			</SS_CALL>
		</BODY>
	</ELEMENT_ITER>
	<SS_CALL>
		DESCR='case of complexType'
		MATCHING_ET='xs:complexType'
		SS_NAME='Element Rep (complexType)'
		PARAMS_EXPR='Array ("...")'
	</SS_CALL>
	<SS_CALL>
		DESCR='case of attribute or attributeGroup'
		MATCHING_ETS={'xs:attribute';'xs:attributeGroup'}
		SS_NAME='Attribute Group Rep'
		PARAMS_EXPR='Array ("...")'
	</SS_CALL>
</ROOT>
<STOCK_SECTIONS>
	<ATTR_ITER>
		MATCHING_ET='xs:anyAttribute'
		FMT={
			sec.outputStyle='text-par';
			txtfl.delimiter.type='nbtxt';
			txtfl.delimiter.text=';\\n ';
		}
		SCOPE='attr-values'
		ATTR='namespace'
		SS_NAME='anyAttribute'
		<BODY>
			<AREA_SEC>
				COND='iterator.value == "##any"'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='any attribute with any namespace'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<AREA_SEC>
				COND='iterator.value == "##other"'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='any attribute with non-schema namespace'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<AREA_SEC>
				COND='iterator.value == "##local"'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='any local attribute (without namespace)'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<AREA_SEC>
				COND='iterator.value == "##targetNamespace"'
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='any attribute with with schema namespace'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<AREA_SEC>
				COND='sectionBlock.execSecNone'
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='space';
						}
						<CTRLS>
							<LABEL>
								TEXT='any attribute with'
							</LABEL>
							<DATA_CTRL>
								FMT={
									text.style='cs4';
								}
								<URL_HLINK>
									TARGET_FRAME_EXPR='"_blank"'
									URL_EXPR='iterator.value.toString()'
								</URL_HLINK>
								FORMULA='iterator.value'
							</DATA_CTRL>
							<LABEL>
								TEXT='namespace'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</BODY>
		<HEADER>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='{'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
		<FOOTER>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<LABEL>
								TEXT='}'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</FOOTER>
	</ATTR_ITER>
	<FOLDER>
		MATCHING_ETS={'xs:attribute';'xs:attributeGroup'}
		FMT={
			sec.outputStyle='table';
			sec.page.keepTogether='true';
			table.sizing='Relative';
			table.cellpadding.both='0';
			table.bkgr.color='#F5F5F5';
			table.border.style='solid';
			table.border.color='#999999';
			table.border.horz.style='none';
			table.border.vert.style='none';
			table.option.borderStylesInHTML='true';
		}
		SS_NAME='Attribute Group Rep'
		<BODY>
			<FOLDER>
				FMT={
					text.style='cs2';
				}
				<BODY>
					<ELEMENT_ITER>
						TARGET_ET='xs:%attribute'
						SCOPE='custom'
						ELEMENT_ENUM_EXPR='rootElement.instanceOf ("xs:attribute") ? Enum (rootElement) : \n{\n  key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\n  findElementsByKey ("content-attributes", key)\n}'
						SORTING='by-lpath'
						SORTING_KEY={lpath='@name|@ref',ascending,case_sensitive}
						<BODY>
							<AREA_SEC>
								COND='getAttrStringValue("name") != ""'
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='21';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													content.outputStyle='text-par';
													ctrl.size.width='75';
													ctrl.size.height='17.3';
													text.style='cs1';
													text.hlink.fmt='style';
													text.hlink.style='cs8';
												}
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"local"';
														'rootElement.id';
													}
												</DOC_HLINK>
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"def"';
													}
												</DOC_HLINK>
												SS_NAME='Attribute QName'
											</SS_CALL_CTRL>
											<LABEL>
												FMT={
													ctrl.size.width='18.8';
													ctrl.size.height='17.3';
													tcell.align.horz='Center';
													text.style='cs9';
												}
												TEXT=' = '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='384.8';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs4';
												}
												SS_NAME='Attribute Value'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<AREA_SEC>
								COND='getAttrStringValue("ref") != ""'
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='20.3';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<DATA_CTRL>
												FMT={
													ctrl.size.width='75';
													ctrl.size.height='17.3';
													text.style='cs1';
													text.hlink.fmt='style';
													text.hlink.style='cs8';
												}
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"local"';
														'rootElement.id';
													}
												</DOC_HLINK>
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"def"';
													}
												</DOC_HLINK>
												<DOC_HLINK>
													TARGET_KEYS={
														'getAttrQNameValue("ref")';
														'"attribute"';
													}
												</DOC_HLINK>
												ATTR='ref'
											</DATA_CTRL>
											<LABEL>
												FMT={
													ctrl.size.width='18.8';
													ctrl.size.height='17.3';
													tcell.align.horz='Center';
													text.style='cs9';
												}
												TEXT=' = '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='385.5';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs4';
												}
												SS_NAME='Attribute Value'
												PASSED_ELEMENT_EXPR='findElementByKey ("global-attributes", getAttrQNameValue("ref"))'
												PASSED_ELEMENT_MATCHING_ET='xs:attribute'
												ALT_FORMULA='"???"'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
					<ELEMENT_ITER>
						FMT={
							text.style='cs2';
						}
						TARGET_ET='xs:anyAttribute'
						SCOPE='custom'
						ELEMENT_ENUM_EXPR='key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\nfindElementsByKey ("content-attributes", key)'
						<BODY>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='21';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													content.outputStyle='text-par';
													ctrl.size.width='478.5';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs1';
													text.font.style.italic='true';
												}
												SS_NAME='anyAttribute'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
				</BODY>
				<HEADER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='1';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='<'
													</LABEL>
													<LABEL>
														FMT={
															text.style='cs10';
														}
														TEXT='...'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
				<FOOTER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='39.8';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs10';
														}
														TEXT='...'
													</LABEL>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</FOOTER>
			</FOLDER>
		</BODY>
		<HEADER>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<PANEL>
								FMT={
									ctrl.size.width='499.5';
									ctrl.size.height='46.5';
									tcell.padding.extra.left='5';
									tcell.padding.extra.right='5';
									tcell.padding.extra.top='5';
								}
								<AREA>
									<CTRL_GROUP>
										FMT={
											par.style='s1';
										}
										<CTRLS>
											<LABEL>
												TEXT='XML Representation Summary'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</PANEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<AREA_SEC>
		MATCHING_ET='xs:%attribute'
		FMT={
			par.option.nowrap='true';
		}
		SS_NAME='Attribute QName'
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<DATA_CTRL>
						FORMULA='schema = getXMLDocument().findChild ("xs:schema");\n\n((form = getAttrStringValue("form")) == "") ? {\n  form = schema.getAttrStringValue ("attributeFormDefault");\n};\n\nname = getAttrStringValue("name");\n\n(form != "qualified") ? name :\n   QName (schema.getAttrStringValue("targetNamespace"), name)'
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<FOLDER>
		MATCHING_ET='xs:%attribute'
		FMT={
			sec.outputStyle='text-par';
		}
		SS_NAME='Attribute Value'
		<BODY>
			<AREA_SEC>
				COND='hasAttr("fixed")'
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='none';
						}
						<CTRLS>
							<LABEL>
								FMT={
									text.style='cs9';
								}
								TEXT='"'
							</LABEL>
							<DATA_CTRL>
								ATTR='fixed'
							</DATA_CTRL>
							<LABEL>
								FMT={
									text.style='cs9';
								}
								TEXT='"'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<FOLDER>
				DESCR='no fixed value'
				COND='! hasAttr("fixed")'
				<BODY>
					<SS_CALL>
						DESCR='if there is \'type\' attribute'
						COND='hasAttr("type")'
						SS_NAME='Simple Content'
						PASSED_ELEMENT_EXPR='type = getAttrStringValue("type");\nqName = QName (type);\n\n((el = findElementByKey ("types", qName)) != null) ? el :\n{\n  el = StubXMLElement();\n  el.setXMLAttribute("name", type);\n  el\n}'
						PASSED_ELEMENT_MATCHING_ETS={'#STUB';'xs:%simpleType'}
						PARAMS_EXPR='Array (true)  // show XML markup'
					</SS_CALL>
					<ELEMENT_ITER>
						DESCR='else, the type is embedded'
						COND='sectionBlock.outputSecNone'
						TARGET_ET='xs:simpleType%xs:localSimpleType'
						SCOPE='simple-location-rules'
						RULES={
							{'*','xs:simpleType'};
						}
						<BODY>
							<SS_CALL>
								SS_NAME='Simple Content'
								PARAMS_EXPR='Array (true)  // show XML markup'
							</SS_CALL>
						</BODY>
						<ELSE>
							DESCR='no type information specified at all'
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												TEXT='anySimpleType'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</ELSE>
					</ELEMENT_ITER>
					<AREA_SEC>
						COND='hasAttr("default")'
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<DELIMITER>
										FMT={
											txtfl.delimiter.type='text';
											txtfl.delimiter.text=' : ';
										}
									</DELIMITER>
									<LABEL>
										FMT={
											text.style='cs9';
										}
										TEXT='"'
									</LABEL>
									<DATA_CTRL>
										ATTR='default'
									</DATA_CTRL>
									<LABEL>
										FMT={
											text.style='cs9';
										}
										TEXT='"'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ETS={'#STUB';'xs:%complexType';'xs:%simpleType'}
		FMT={
			sec.outputStyle='text-par';
		}
		SS_NAME='Element Content'
		<BODY>
			<TEMPLATE_CALL>
				DESCR='in case of complexType, try to built a complex or mixed content model representation'
				MATCHING_ET='xs:%complexType'
				FMT={
					text.style='cs5';
				}
				TEMPLATE_FILE='../type/contentModel.tpl'
				PASSED_PARAMS={
					'owner_id','rootElement.id';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<FOLDER>
				DESCR='otherwise, this is a simpleType or a complexType with simple content'
				COND='sectionBlock.outputSecNone'
				MATCHING_ETS={'#STUB';'xs:%complexType';'xs:%simpleType'}
				FMT={
					text.style='cs3';
				}
				<BODY>
					<FOLDER>
						DESCR='in case the template\'s root element is \'%element\', some settings specified in it need to be printed; (switching to it the current context element)'
						CONTEXT_ELEMENT_EXPR='rootElement'
						MATCHING_ET='xs:%element'
						<BODY>
							<FOLDER>
								DESCR='when \'fixed\' attr specified and its value is not empty (the empty value defines EMPTY content model!)'
								COND='getAttrValue("fixed") != ""'
								<BODY>
									<AREA_SEC>
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														TEXT='"'
													</LABEL>
													<DATA_CTRL>
														ATTR='fixed'
													</DATA_CTRL>
													<LABEL>
														TEXT='"'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</FOLDER>
							<FOLDER>
								DESCR='no \'fixed\' attribute'
								COND='! hasAttr("fixed")'
								<BODY>
									<SS_CALL>
										DESCR='print type info (back to the element received by this stock-section)'
										SS_NAME='Simple Content'
										PASSED_ELEMENT_EXPR='stockSection.contextElement'
										PASSED_ELEMENT_MATCHING_ETS={'#STUB';'xs:%complexType';'xs:%simpleType'}
									</SS_CALL>
									<AREA_SEC>
										COND='hasAttr("default")'
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<DELIMITER>
														FMT={
															txtfl.delimiter.type='text';
															txtfl.delimiter.text=' : ';
														}
													</DELIMITER>
													<LABEL>
														TEXT='"'
													</LABEL>
													<DATA_CTRL>
														ATTR='default'
													</DATA_CTRL>
													<LABEL>
														TEXT='"'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</FOLDER>
						</BODY>
					</FOLDER>
					<SS_CALL>
						DESCR='otherwise, just print type info'
						COND='sectionBlock.execSecNone'
						SS_NAME='Simple Content'
					</SS_CALL>
				</BODY>
				<HEADER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs11';
										}
										TEXT='{ '
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
				<FOOTER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs11';
										}
										TEXT=' }'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</FOOTER>
			</FOLDER>
		</BODY>
	</FOLDER>
	<FOLDER>
		DESCR='param: element\'s qualified name'
		MATCHING_ET='xs:%complexType'
		FMT={
			sec.outputStyle='table';
			sec.page.keepTogether='true';
			table.sizing='Relative';
			table.cellpadding.both='0';
			table.bkgr.color='#F5F5F5';
			table.border.style='solid';
			table.border.color='#999999';
			table.border.horz.style='none';
			table.border.vert.style='none';
			table.option.borderStylesInHTML='true';
		}
		SS_NAME='Element Rep (complexType)'
		<BODY>
			<FOLDER>
				DESCR='NON-EMPTY CONTENT'
				COND='checkStockSectionOutput("Element Content");'
				FMT={
					text.style='cs2';
				}
				<BODY>
					<FOLDER>
						<BODY>
							<ELEMENT_ITER>
								TARGET_ET='xs:%attribute'
								SCOPE='custom'
								ELEMENT_ENUM_EXPR='rootElement.instanceOf ("xs:attribute") ? Enum (rootElement) : \n{\n  key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\n  findElementsByKey ("content-attributes", key)\n}'
								SORTING='by-expr'
								SORTING_KEY={expr='hasAttr("name") ? callStockSection("Attribute QName") : getAttrStringValue("ref")',ascending,case_sensitive}
								<BODY>
									<AREA_SEC>
										COND='getAttrStringValue("name") != ""'
										<AREA>
											<CTRL_GROUP>
												FMT={
													trow.align.vert='Top';
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															ctrl.size.width='21.8';
															ctrl.size.height='17.3';
															tcell.padding.extra.left='5';
															text.option.nbsps='true';
														}
														TEXT='   '
													</LABEL>
													<SS_CALL_CTRL>
														FMT={
															content.outputStyle='text-par';
															ctrl.size.width='75';
															ctrl.size.height='17.3';
															text.style='cs1';
															text.hlink.fmt='style';
															text.hlink.style='cs8';
														}
														<DOC_HLINK>
															TARGET_KEYS={
																'contextElement.id';
																'"local"';
																'rootElement.id';
															}
														</DOC_HLINK>
														<DOC_HLINK>
															TARGET_KEYS={
																'contextElement.id';
																'"def"';
															}
														</DOC_HLINK>
														SS_NAME='Attribute QName'
													</SS_CALL_CTRL>
													<LABEL>
														FMT={
															ctrl.size.width='18.8';
															ctrl.size.height='17.3';
															tcell.align.horz='Center';
															text.style='cs9';
														}
														TEXT=' = '
													</LABEL>
													<SS_CALL_CTRL>
														FMT={
															ctrl.size.width='384';
															ctrl.size.height='17.3';
															tcell.sizing='Relative';
															tcell.padding.extra.right='5';
															text.style='cs4';
														}
														SS_NAME='Attribute Value'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
									<AREA_SEC>
										COND='getAttrStringValue("ref") != ""'
										<AREA>
											<CTRL_GROUP>
												FMT={
													trow.align.vert='Top';
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															ctrl.size.width='21';
															ctrl.size.height='17.3';
															tcell.padding.extra.left='5';
															text.option.nbsps='true';
														}
														TEXT='   '
													</LABEL>
													<DATA_CTRL>
														FMT={
															ctrl.size.width='75';
															ctrl.size.height='17.3';
															text.style='cs1';
															text.hlink.fmt='style';
															text.hlink.style='cs8';
														}
														<DOC_HLINK>
															TARGET_KEYS={
																'contextElement.id';
																'"local"';
																'rootElement.id';
															}
														</DOC_HLINK>
														<DOC_HLINK>
															TARGET_KEYS={
																'contextElement.id';
																'"def"';
															}
														</DOC_HLINK>
														<DOC_HLINK>
															TARGET_KEYS={
																'getAttrQNameValue("ref")';
																'"attribute"';
															}
														</DOC_HLINK>
														ATTR='ref'
													</DATA_CTRL>
													<LABEL>
														FMT={
															ctrl.size.width='18.8';
															ctrl.size.height='17.3';
															tcell.align.horz='Center';
															text.style='cs9';
														}
														TEXT=' = '
													</LABEL>
													<SS_CALL_CTRL>
														FMT={
															ctrl.size.width='384.8';
															ctrl.size.height='17.3';
															tcell.sizing='Relative';
															tcell.padding.extra.right='5';
															text.style='cs4';
														}
														SS_NAME='Attribute Value'
														PASSED_ELEMENT_EXPR='findElementByKey ("global-attributes", getAttrQNameValue("ref"))'
														PASSED_ELEMENT_MATCHING_ET='xs:attribute'
														ALT_FORMULA='"???"'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</ELEMENT_ITER>
							<ELEMENT_ITER>
								FMT={
									text.style='cs2';
								}
								TARGET_ET='xs:anyAttribute'
								SCOPE='custom'
								ELEMENT_ENUM_EXPR='key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\nfindElementsByKey ("content-attributes", key)'
								<BODY>
									<AREA_SEC>
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															ctrl.size.width='21';
															ctrl.size.height='17.3';
															tcell.padding.extra.left='5';
															text.option.nbsps='true';
														}
														TEXT='   '
													</LABEL>
													<SS_CALL_CTRL>
														FMT={
															content.outputStyle='text-par';
															ctrl.size.width='478.5';
															ctrl.size.height='17.3';
															tcell.sizing='Relative';
															tcell.padding.extra.right='5';
															text.style='cs1';
															text.font.style.italic='true';
														}
														SS_NAME='anyAttribute'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</ELEMENT_ITER>
						</BODY>
						<HEADER>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<PANEL>
												FMT={
													ctrl.size.width='499.5';
													ctrl.size.height='39.8';
													tcell.padding.extra.left='5';
													tcell.padding.extra.right='5';
												}
												<AREA>
													<CTRL_GROUP>
														FMT={
															txtfl.delimiter.type='none';
														}
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs9';
																}
																TEXT='<'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	text.style='cs10';
																}
																FORMULA='stockSection.param'
															</DATA_CTRL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</HEADER>
						<FOOTER>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='19.5';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<LABEL>
												FMT={
													ctrl.size.width='480';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs9';
												}
												TEXT='>'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</FOOTER>
						<ELSE>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										FMT={
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<PANEL>
												FMT={
													ctrl.size.width='499.5';
													ctrl.size.height='38.3';
													tcell.padding.extra.left='5';
													tcell.padding.extra.right='5';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs9';
																}
																TEXT='<'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	text.style='cs10';
																}
																FORMULA='stockSection.param'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs9';
																}
																TEXT='>'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</ELSE>
					</FOLDER>
					<AREA_SEC>
						COND='! getBooleanParam("fmt.allowNestedTables")'
						FMT={
							table.border.style='none';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									trow.align.vert='Top';
								}
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											text.option.nbsps='true';
										}
										TEXT='   '
									</LABEL>
									<PANEL>
										FMT={
											ctrl.size.width='75';
											ctrl.size.height='38.3';
											tcell.padding.extra.top='1';
											txtfl.delimiter.type='none';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.font.style.italic='true';
														}
														TEXT='Content:'
													</LABEL>
													<LABEL>
														FMT={
															text.option.nbsps='true';
														}
														TEXT=' '
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
									<SS_CALL_CTRL>
										FMT={
											ctrl.size.width='403.5';
											ctrl.size.height='38.3';
											tcell.sizing='Relative';
											tcell.padding.extra.right='5';
										}
										SS_NAME='Element Content'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='getBooleanParam("fmt.allowNestedTables")'
						FMT={
							table.border.style='none';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									trow.align.vert='Top';
								}
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='21';
											ctrl.size.height='59.3';
											tcell.padding.extra.left='5';
											text.option.nbsps='true';
										}
										TEXT='   '
									</LABEL>
									<PANEL>
										FMT={
											content.outputStyle='table';
											ctrl.size.width='478.5';
											ctrl.size.height='59.3';
											tcell.sizing='Relative';
											table.sizing='Relative';
											table.cellpadding.both='0';
											table.border.style='none';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													trow.align.vert='Top';
												}
												<CTRLS>
													<PANEL>
														FMT={
															ctrl.size.width='75';
															ctrl.size.height='38.3';
															tcell.padding.extra.top='1';
															txtfl.delimiter.type='none';
														}
														<AREA>
															<CTRL_GROUP>
																<CTRLS>
																	<LABEL>
																		FMT={
																			text.font.style.italic='true';
																		}
																		TEXT='Content:'
																	</LABEL>
																	<LABEL>
																		FMT={
																			text.option.nbsps='true';
																		}
																		TEXT=' '
																	</LABEL>
																</CTRLS>
															</CTRL_GROUP>
														</AREA>
													</PANEL>
													<SS_CALL_CTRL>
														FMT={
															ctrl.size.width='381';
															ctrl.size.height='38.3';
															tcell.sizing='Relative';
															tcell.padding.extra.right='5';
														}
														SS_NAME='Element Content'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<FOOTER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='</'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</FOOTER>
			</FOLDER>
			<FOLDER>
				DESCR='EMPTY CONTENT'
				COND='sectionBlock.execSecNone'
				FMT={
					text.style='cs2';
				}
				COLLAPSED
				<BODY>
					<ELEMENT_ITER>
						TARGET_ET='xs:%attribute'
						SCOPE='custom'
						ELEMENT_ENUM_EXPR='rootElement.instanceOf ("xs:attribute") ? Enum (rootElement) : \n{\n  key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\n  findElementsByKey ("content-attributes", key)\n}'
						SORTING='by-expr'
						SORTING_KEY={expr='hasAttr("name") ? callStockSection("Attribute QName") : getAttrStringValue("ref")',ascending,case_sensitive}
						<BODY>
							<AREA_SEC>
								COND='getAttrStringValue("name") != ""'
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='21';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													content.outputStyle='text-par';
													ctrl.size.width='75';
													ctrl.size.height='17.3';
													text.style='cs1';
													text.hlink.fmt='style';
													text.hlink.style='cs8';
												}
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"local"';
														'rootElement.id';
													}
												</DOC_HLINK>
												SS_NAME='Attribute QName'
											</SS_CALL_CTRL>
											<LABEL>
												FMT={
													ctrl.size.width='18.8';
													ctrl.size.height='17.3';
													tcell.align.horz='Center';
													text.style='cs9';
												}
												TEXT=' = '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='384.8';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs4';
												}
												SS_NAME='Attribute Value'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<AREA_SEC>
								COND='getAttrStringValue("ref") != ""'
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='20.3';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<DATA_CTRL>
												FMT={
													ctrl.size.width='75';
													ctrl.size.height='17.3';
													text.style='cs1';
													text.hlink.fmt='style';
													text.hlink.style='cs8';
												}
												<DOC_HLINK>
													TARGET_KEYS={
														'contextElement.id';
														'"local"';
														'rootElement.id';
													}
												</DOC_HLINK>
												ATTR='ref'
											</DATA_CTRL>
											<LABEL>
												FMT={
													ctrl.size.width='18.8';
													ctrl.size.height='17.3';
													tcell.align.horz='Center';
													text.style='cs9';
												}
												TEXT=' = '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='385.5';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs4';
												}
												SS_NAME='Attribute Value'
												PASSED_ELEMENT_EXPR='findElementByKey ("global-attributes", getAttrQNameValue("ref"))'
												PASSED_ELEMENT_MATCHING_ET='xs:attribute'
												ALT_FORMULA='"???"'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
					<ELEMENT_ITER>
						FMT={
							text.style='cs2';
						}
						TARGET_ET='xs:anyAttribute'
						SCOPE='custom'
						ELEMENT_ENUM_EXPR='key = (rootElement.instanceOf ("xs:%element") && rootElement.getAttrValue("type") != "")\n       ? findElementByKey ("types", rootElement.getAttrQNameValue("type")).id\n       : rootElement.id;\n\nfindElementsByKey ("content-attributes", key)'
						<BODY>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='21';
													ctrl.size.height='17.3';
													tcell.padding.extra.left='5';
													tcell.option.nowrap='true';
													text.option.nbsps='true';
												}
												TEXT='   '
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													content.outputStyle='text-par';
													ctrl.size.width='478.5';
													ctrl.size.height='17.3';
													tcell.sizing='Relative';
													tcell.padding.extra.right='5';
													text.style='cs1';
													text.font.style.italic='true';
												}
												SS_NAME='anyAttribute'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
				</BODY>
				<HEADER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='<'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
				<FOOTER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='17.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
											text.style='cs9';
										}
										TEXT='/>'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</FOOTER>
				<ELSE>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='39.8';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='<'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='/>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</ELSE>
			</FOLDER>
		</BODY>
		<HEADER>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<PANEL>
								FMT={
									ctrl.size.width='499.5';
									ctrl.size.height='46.5';
									tcell.padding.extra.left='5';
									tcell.padding.extra.right='5';
									tcell.padding.extra.top='5';
								}
								<AREA>
									<CTRL_GROUP>
										FMT={
											par.style='s1';
										}
										<CTRLS>
											<LABEL>
												TEXT='XML Representation Summary'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</PANEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<FOLDER>
		DESCR='param: element\'s qualified name'
		MATCHING_ETS={'#STUB';'xs:%simpleType'}
		FMT={
			sec.outputStyle='table';
			sec.page.keepTogether='true';
			table.sizing='Relative';
			table.cellpadding.both='0';
			table.bkgr.color='#F5F5F5';
			table.border.style='solid';
			table.border.color='#999999';
			table.border.horz.style='none';
			table.border.vert.style='none';
			table.option.borderStylesInHTML='true';
		}
		SS_NAME='Element Rep (simpleType)'
		<BODY>
			<FOLDER>
				DESCR='NON-EMPTY CONTENT'
				COND='checkStockSectionOutput("Element Content")'
				FMT={
					text.style='cs2';
				}
				<BODY>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									trow.align.vert='Top';
								}
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='23.3';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											text.option.nbsps='true';
										}
										TEXT='   '
									</LABEL>
									<PANEL>
										FMT={
											ctrl.size.width='75';
											ctrl.size.height='38.3';
											txtfl.delimiter.type='none';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.font.style.italic='true';
														}
														TEXT='Content:'
													</LABEL>
													<LABEL>
														FMT={
															text.option.nbsps='true';
														}
														TEXT=' '
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
									<SS_CALL_CTRL>
										FMT={
											ctrl.size.width='401.3';
											ctrl.size.height='38.3';
											tcell.sizing='Relative';
											tcell.padding.extra.right='5';
										}
										SS_NAME='Element Content'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
				<HEADER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='<'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
													<LABEL>
														COND='iterator.isLastItem'
														FMT={
															text.style='cs9';
														}
														TEXT='>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
				<FOOTER>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='38.3';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='</'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</FOOTER>
			</FOLDER>
			<FOLDER>
				DESCR='EMPTY CONTENT'
				COND='sectionBlock.execSecNone'
				FMT={
					text.style='cs2';
				}
				<BODY>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<PANEL>
										FMT={
											ctrl.size.width='499.5';
											ctrl.size.height='39.8';
											tcell.padding.extra.left='5';
											tcell.padding.extra.right='5';
											tcell.padding.extra.bottom='5';
										}
										<AREA>
											<CTRL_GROUP>
												<CTRLS>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='<'
													</LABEL>
													<DATA_CTRL>
														FMT={
															text.style='cs10';
														}
														FORMULA='stockSection.param'
													</DATA_CTRL>
													<LABEL>
														FMT={
															text.style='cs9';
														}
														TEXT='/>'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</PANEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
		</BODY>
		<HEADER>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<PANEL>
								FMT={
									ctrl.size.width='499.5';
									ctrl.size.height='46.5';
									tcell.padding.extra.left='5';
									tcell.padding.extra.right='5';
									tcell.padding.extra.top='5';
								}
								<AREA>
									<CTRL_GROUP>
										FMT={
											par.style='s1';
										}
										<CTRLS>
											<LABEL>
												TEXT='XML Representation Summary'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</PANEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<FOLDER>
		DESCR='Simple Content Representation'
		MATCHING_ETS={'#STUB';'xs:%complexType';'xs:%simpleType'}
		FMT={
			sec.outputStyle='text-par';
		}
		SS_NAME='Simple Content'
		<BODY>
			<TEMPLATE_CALL>
				MATCHING_ETS={'xs:%complexType';'xs:%simpleType'}
				TEMPLATE_FILE='../type/simpleContentRep.tpl'
				PASSED_PARAMS={
					'showMarkup','stockSection.param.toBoolean()';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<FOLDER>
				MATCHING_ET='#STUB'
				FMT={
					par.option.nowrap='true';
				}
				<BODY>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<DATA_CTRL>
										FORMULA='getAttrValue("name")'
									</DATA_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
		</BODY>
	</FOLDER>
</STOCK_SECTIONS>
CHECKSUM='lgxjXHkaghWMNWAkmPRlpA'
</DOCFLEX_TEMPLATE>