<DOCFLEX_TEMPLATE VER='1.7'>
CREATED='2004-06-21 01:50:00'
LAST_UPDATE='2006-10-09 06:34:51'
DESIGNER_TOOL='DocFlex SDK 1.0'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='xsddoc'
ROOT_ET='xs:schema'
<TEMPLATE_PARAMS>
	PARAM={
		param.name='doc.schema.profile';
		param.displayName='Schema Profile';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.annotation';
		param.displayName='Annotation';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.element';
		param.displayName='Element Summary';
		param.type='enum';
		param.enum.values='all\nglobal\nlocal\nglobal_local\nnone';
	}
	PARAM={
		param.name='doc.schema.cs.complexType';
		param.displayName='Complex Type Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.simpleType';
		param.displayName='Simple Type Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.group';
		param.displayName='Element Group Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.attribute';
		param.displayName='Global Attribute Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.cs.attributeGroup';
		param.displayName='Attribute Group Summary';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='doc.schema.xmlSource';
		param.displayName='XML Source';
		param.description='Specifies if the XML source of the whole XML schema should be reproduced within the <i>Schema Overview</i> documentation.';
		param.type='boolean';
		param.boolean.default='true';
	}
	PARAM={
		param.name='sec.xmlSource.box.schema';
		param.displayName='Schemas';
		param.type='boolean';
		param.boolean.default='true';
	}
</TEMPLATE_PARAMS>
<HTARGET>
	TARGET_KEYS={
		'contextElement.id';
		'"detail"';
	}
</HTARGET>
<HTARGET>
	TARGET_KEYS={
		'getXMLDocument().id';
		'"detail"';
	}
</HTARGET>
FMT={
	doc.lengthUnits='pt';
	doc.hlink.style.link='cs3';
}
<STYLES>
	CHAR_STYLE={
		style.name='Code';
		style.id='cs1';
		text.font.name='Courier New';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs2';
		style.default='true';
	}
	PAR_STYLE={
		style.name='Detail Heading 1';
		style.id='s1';
		text.font.size='12';
		text.font.style.bold='true';
		par.bkgr.opaque='true';
		par.bkgr.color='#CCCCFF';
		par.border.style='solid';
		par.border.color='#666666';
		par.margin.top='12';
		par.margin.bottom='10';
		par.padding.left='2.5';
		par.padding.right='2.5';
		par.padding.top='2';
		par.padding.bottom='2';
		par.page.keepWithNext='true';
	}
	PAR_STYLE={
		style.name='Detail Heading 2';
		style.id='s2';
		text.font.size='10';
		text.font.style.bold='true';
		par.bkgr.opaque='true';
		par.bkgr.color='#EEEEFF';
		par.border.style='solid';
		par.border.color='#666666';
		par.margin.top='12';
		par.margin.bottom='8';
		par.padding.left='2';
		par.padding.right='2';
		par.padding.top='2';
		par.padding.bottom='2';
		par.page.keepWithNext='true';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs3';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	CHAR_STYLE={
		style.name='Internal Subset';
		style.id='cs4';
		text.font.name='Courier New';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Main Heading';
		style.id='s3';
		text.font.name='Verdana';
		text.font.size='13';
		text.font.style.bold='true';
		text.color.foreground='#4477AA';
		par.bkgr.opaque='true';
		par.bkgr.color='#EEEEEE';
		par.border.style='solid';
		par.border.color='#4477AA';
		par.margin.top='0';
		par.margin.bottom='9';
		par.padding.left='5';
		par.padding.right='5';
		par.padding.top='3';
		par.padding.bottom='3';
		par.page.keepTogether='true';
		par.page.keepWithNext='true';
	}
	CHAR_STYLE={
		style.name='Markup';
		style.id='cs5';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s4';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Normal Smaller';
		style.id='cs6';
		text.font.name='Arial';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Page Header Font';
		style.id='cs7';
		text.font.name='Arial';
		text.font.style.italic='true';
	}
	CHAR_STYLE={
		style.name='Page Number';
		style.id='cs8';
		text.font.size='9';
		text.font.style.italic='true';
	}
	CHAR_STYLE={
		style.name='Summary Heading Font';
		style.id='cs9';
		text.font.size='12';
		text.font.style.bold='true';
	}
	CHAR_STYLE={
		style.name='XML Source';
		style.id='cs10';
		text.font.name='Verdana';
		text.font.size='8';
	}
</STYLES>
<PAGE_HEADER>
	<AREA_SEC>
		FMT={
			text.style='cs7';
			table.cellpadding.both='0';
			table.border.style='none';
			table.border.bottom.style='solid';
		}
		<AREA>
			<CTRL_GROUP>
				FMT={
					par.border.bottom.style='solid';
				}
				<CTRLS>
					<LABEL>
						TEXT='XML Schema'
					</LABEL>
					<DATA_CTRL>
						FORMULA='\'"\' + getXMLDocument().getAttrStringValue("xmlName") + \'"\''
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
</PAGE_HEADER>
<ROOT>
	<AREA_SEC>
		FMT={
			par.style='s3';
		}
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<LABEL>
						TEXT='XML Schema'
					</LABEL>
					<DATA_CTRL>
						FMT={
							text.font.style.italic='true';
						}
						FORMULA='\'"\' + getXMLDocument().getAttrStringValue("xmlName") + \'"\''
					</DATA_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<TEMPLATE_CALL>
		COND='getBooleanParam("doc.schema.profile")'
		FMT={
			sec.spacing.before='12';
		}
		TEMPLATE_FILE='schemaProfile.tpl'
		PASSED_PARAMS={
			'schema-summary','true';
		}
		OUTPUT_TYPE='included'
		DSM_MODE='pass-current-model'
	</TEMPLATE_CALL>
	<FOLDER>
		DESCR='Annotation'
		COND='getBooleanParam("doc.schema.annotation")'
		<BODY>
			<TEMPLATE_CALL>
				FMT={
					text.style='cs6';
				}
				TEMPLATE_FILE='../misc/annotation.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s2';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							trow.bkgr.color='#CCCCFF';
						}
						<CTRLS>
							<LABEL>
								TEXT='Annotation'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<FOLDER>
		DESCR='COMPONENT SUMMARY'
		FMT={
			sec.spacing.before='14';
		}
		COLLAPSED
		<BODY>
			<TEMPLATE_CALL>
				DESCR='all elements'
				COND='getStringParam("doc.schema.cs.element") == "all"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='allElementSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='global elements'
				COND='param = getStringParam("doc.schema.cs.element");\nparam == "global" || param == "global_local"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='globalElementSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='local elements'
				COND='param = getStringParam("doc.schema.cs.element");\nparam == "local" || param == "global_local"'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='localElementSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='complexTypes'
				COND='getBooleanParam("doc.schema.cs.complexType")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='complexTypeSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='simpleTypes'
				COND='getBooleanParam("doc.schema.cs.simpleType")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='simpleTypeSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='element groups'
				COND='getBooleanParam("doc.schema.cs.group")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='groupSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='attributes'
				COND='getBooleanParam("doc.schema.cs.attribute")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='attributeSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
			<TEMPLATE_CALL>
				DESCR='attribute groups'
				COND='getBooleanParam("doc.schema.cs.attributeGroup")'
				FMT={
					sec.spacing.before='12';
				}
				TEMPLATE_FILE='attributeGroupSummary.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		DESCR='XML SOURCE'
		COND='getBooleanParam("doc.schema.xmlSource")'
		FMT={
			sec.spacing.before='14';
		}
		<HTARGET>
			TARGET_KEYS={
				'contextElement.id';
				'"xml-source"';
			}
		</HTARGET>
		COLLAPSED
		<BODY>
			<AREA_SEC>
				COND='getBooleanParam("sec.xmlSource.box.schema")'
				FMT={
					sec.outputStyle='table';
					table.sizing='Relative';
					table.autofit='false';
					table.cellpadding.both='5';
					table.bkgr.color='#F5F5F5';
					table.border.style='solid';
					table.border.color='#999999';
					table.option.borderStylesInHTML='true';
				}
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<SS_CALL_CTRL>
								FMT={
									ctrl.size.width='499.5';
									ctrl.size.height='17.3';
								}
								SS_NAME='XML Source'
								PASSED_ELEMENT_EXPR='getXMLDocument()'
								PASSED_ELEMENT_MATCHING_ET='#DOCUMENT'
							</SS_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<SS_CALL>
				COND='! getBooleanParam("sec.xmlSource.box.schema")'
				SS_NAME='XML Source'
				PASSED_ELEMENT_EXPR='getXMLDocument()'
				PASSED_ELEMENT_MATCHING_ET='#DOCUMENT'
			</SS_CALL>
		</BODY>
		<HEADER>
			<AREA_SEC>
				FMT={
					par.style='s1';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							trow.bkgr.color='#CCCCFF';
						}
						<CTRLS>
							<LABEL>
								TEXT='XML Source'
							</LABEL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</HEADER>
	</FOLDER>
	<TEMPLATE_CALL>
		DESCR='Bottom Message'
		COND='output.type == "document"'
		TEMPLATE_FILE='../about.tpl'
		OUTPUT_TYPE='included'
		DSM_MODE='pass-current-model'
	</TEMPLATE_CALL>
</ROOT>
<STOCK_SECTIONS>
	<FOLDER>
		MATCHING_ET='xs:attribute'
		SS_NAME='Attribte'
		<BODY>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						FMT={
							par.margin.bottom='6';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.option.text.collapseSpaces='true';
									ctrl.option.text.noBlankOutput='true';
									text.style='cs6';
									text.option.renderNLs='false';
								}
								FORMULA='firstSentence (mergeStrings (\n  getValuesByLPath ("xs:annotation/xs:documentation//(#TEXT | #CDATA)")\n))'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../attribute/attributeProfile.tpl'
				PASSED_PARAMS={
					'nsURI','rootElement.getAttrStringValue("targetNamespace")';
					'showSchema','false';
					'showNS','false';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:attributeGroup'
		SS_NAME='Attribte Group'
		<BODY>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						FMT={
							par.margin.bottom='6';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.option.text.collapseSpaces='true';
									ctrl.option.text.noBlankOutput='true';
									text.style='cs6';
									text.option.renderNLs='false';
								}
								FORMULA='firstSentence (mergeStrings (\n  getValuesByLPath ("xs:annotation/xs:documentation//(#TEXT | #CDATA)")\n))'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../groups/attributeGroupProfile.tpl'
				PASSED_PARAMS={
					'nsURI','rootElement.getAttrStringValue("targetNamespace")';
					'showSchema','false';
					'showNS','false';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:%element'
		SS_NAME='Element'
		<BODY>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						FMT={
							par.margin.bottom='6';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.option.text.collapseSpaces='true';
									ctrl.option.text.noBlankOutput='true';
									text.style='cs6';
									text.option.renderNLs='false';
								}
								FORMULA='firstSentence (mergeStrings (\n  getValuesByLPath ("xs:annotation/xs:documentation//(#TEXT | #CDATA)")\n))'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../element/elementProfile.tpl'
				PASSED_PARAMS={
					'nsURI','rootElement.getAttrStringValue("targetNamespace")';
					'showSchema','false';
					'showNS','false';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:group'
		SS_NAME='Element Group'
		<BODY>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						FMT={
							par.margin.bottom='6';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.option.text.collapseSpaces='true';
									ctrl.option.text.noBlankOutput='true';
									text.style='cs6';
									text.option.renderNLs='false';
								}
								FORMULA='firstSentence (mergeStrings (\n  getValuesByLPath ("xs:annotation/xs:documentation//(#TEXT | #CDATA)")\n))'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../groups/groupProfile.tpl'
				PASSED_PARAMS={
					'nsURI','rootElement.getAttrStringValue("targetNamespace")';
					'showSchema','false';
					'showNS','false';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<AREA_SEC>
		MATCHING_ET='xs:%localElement'
		FMT={
			sec.outputStyle='text-par';
			txtfl.delimiter.type='none';
		}
		SS_NAME='Local Element Name'
		<AREA>
			<CTRL_GROUP>
				<CTRLS>
					<DATA_CTRL>
						<DOC_HLINK>
							TARGET_KEYS={
								'contextElement.id';
								'"detail"';
							}
						</DOC_HLINK>
						FORMULA='name = getAttrStringValue("name");\nnsURI = rootElement.getAttrStringValue("targetNamespace");\n\n((form = getAttrStringValue("form")) == "") ? {\n  schema = getXMLDocument().findChild ("xs:schema");\n  form = schema.getAttrStringValue ("elementFormDefault");\n};\n\nform != "qualified" ? name : QName (nsURI, name)'
					</DATA_CTRL>
					<TEMPLATE_CALL_CTRL>
						FMT={
							text.font.style.bold='false';
						}
						TEMPLATE_FILE='../element/localElementExt.tpl'
						OUTPUT_TYPE='included'
						DSM_MODE='pass-current-model'
					</TEMPLATE_CALL_CTRL>
				</CTRLS>
			</CTRL_GROUP>
		</AREA>
	</AREA_SEC>
	<FOLDER>
		MATCHING_ETS={'xs:complexType';'xs:simpleType'}
		SS_NAME='Type'
		<BODY>
			<AREA_SEC>
				<AREA>
					<CTRL_GROUP>
						FMT={
							par.margin.bottom='6';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.option.text.collapseSpaces='true';
									ctrl.option.text.noBlankOutput='true';
									text.style='cs6';
									text.option.renderNLs='false';
								}
								FORMULA='firstSentence (mergeStrings (\n  getValuesByLPath ("xs:annotation/xs:documentation//(#TEXT | #CDATA)")\n))'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<TEMPLATE_CALL>
				TEMPLATE_FILE='../type/typeProfile.tpl'
				PASSED_PARAMS={
					'nsURI','rootElement.getAttrStringValue("targetNamespace")';
					'showSchema','false';
					'showNS','false';
				}
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='#DOCUMENT'
		SS_NAME='XML Source'
		<BODY>
			<AREA_SEC>
				DESCR='XML declaration'
				COND='getAttrValue("xmlDecl") != ""'
				FMT={
					text.style='cs10';
				}
				<AREA>
					<CTRL_GROUP>
						FMT={
							txtfl.delimiter.type='none';
						}
						<CTRLS>
							<DATA_CTRL>
								FMT={
									text.style='cs5';
								}
								ATTR='xmlDecl'
							</DATA_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
			<ELEMENT_ITER>
				DESCR='iterates by all nodes in the XML'
				FMT={
					text.style='cs10';
				}
				TARGET_ET='<ANY>'
				SCOPE='simple-location-rules'
				RULES={
					{'*','*'};
				}
				<BODY>
					<FOLDER>
						DESCR='processes <!DOCTYPE> node'
						MATCHING_ET='#DOCTYPE'
						<BODY>
							<AREA_SEC>
								DESCR='simple case of <!DOCTYPE> node'
								COND='getAttrStringValue("internalSubset") == ""'
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='<!DOCTYPE'
											</LABEL>
											<DATA_CTRL>
												FMT={
													text.style='cs5';
												}
												ATTR='name'
											</DATA_CTRL>
											<PANEL>
												COND='getAttrStringValue("publicId") != ""'
												FMT={
													ctrl.size.width='132';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='PUBLIC'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='publicId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<PANEL>
												COND='getAttrStringValue("systemId") != ""'
												FMT={
													ctrl.size.width='137.3';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																COND='getAttrStringValue("publicId") == ""'
																FMT={
																	text.style='cs5';
																}
																TEXT='SYSTEM'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='systemId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<DELIMITER>
												FMT={
													text.style='cs5';
													txtfl.delimiter.type='none';
												}
											</DELIMITER>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='>'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<AREA_SEC>
								DESCR='<!DOCTYPE> node with Internal Subset'
								COND='getAttrStringValue("internalSubset") != ""'
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='<!DOCTYPE'
											</LABEL>
											<DATA_CTRL>
												FMT={
													text.style='cs5';
												}
												ATTR='name'
											</DATA_CTRL>
											<PANEL>
												COND='getAttrStringValue("publicId") != ""'
												FMT={
													ctrl.size.width='130.5';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='PUBLIC'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='publicId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<PANEL>
												COND='getAttrStringValue("systemId") != ""'
												FMT={
													ctrl.size.width='137.3';
													txtfl.delimiter.type='none';
												}
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<LABEL>
																COND='getAttrStringValue("publicId") == ""'
																FMT={
																	text.style='cs5';
																}
																TEXT='SYSTEM'
															</LABEL>
															<DELIMITER>
															</DELIMITER>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
															<DATA_CTRL>
																FMT={
																	ctrl.option.text.noBlankOutput='true';
																	text.style='cs5';
																}
																ATTR='systemId'
															</DATA_CTRL>
															<LABEL>
																FMT={
																	text.style='cs5';
																}
																TEXT='"'
															</LABEL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</PANEL>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT='['
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
									<CTRL_GROUP>
										FMT={
											par.margin.left='10';
										}
										<CTRLS>
											<DATA_CTRL>
												FMT={
													ctrl.option.text.trimSpaces='true';
													text.style='cs4';
													text.option.renderNLs='true';
												}
												ATTR='internalSubset'
											</DATA_CTRL>
										</CTRLS>
									</CTRL_GROUP>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													text.style='cs5';
												}
												TEXT=']>'
											</LABEL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</FOLDER>
					<TEMPLATE_CALL>
						DESCR='processes other XML nodes'
						COND='sectionBlock.execSecNone'
						TEMPLATE_FILE='../misc/nodeSource.tpl'
						PASSED_PARAMS={
							'bookmark_xmlns','true';
						}
						OUTPUT_TYPE='included'
						DSM_MODE='pass-current-model'
					</TEMPLATE_CALL>
				</BODY>
			</ELEMENT_ITER>
		</BODY>
	</FOLDER>
</STOCK_SECTIONS>
CHECKSUM='TpKAr4PXssLTqbgBr6eD5A'
</DOCFLEX_TEMPLATE>