/*
 * All content copyright (c) 2003-2008 Terracotta, Inc., except as may otherwise be noted in a separate copyright notice.  All rights reserved.
 */

/* Generated By:JJTree: Do not edit this line. D:/aw/cvs_aw/aspectwerkz4/src/main/org/codehaus/aspectwerkz/expression/ast\ExpressionParserTreeConstants.java */

package com.tc.aspectwerkz.expression.ast;

public interface ExpressionParserTreeConstants {
  public int JJTROOT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTNOT = 5;
  public int JJTPOINTCUTREFERENCE = 6;
  public int JJTEXECUTION = 7;
  public int JJTCALL = 8;
  public int JJTSET = 9;
  public int JJTGET = 10;
  public int JJTHANDLER = 11;
  public int JJTWITHIN = 12;
  public int JJTWITHINCODE = 13;
  public int JJTSTATICINITIALIZATION = 14;
  public int JJTCLASSPATTERN = 15;
  public int JJTCFLOW = 16;
  public int JJTCFLOWBELOW = 17;
  public int JJTARGS = 18;
  public int JJTHASMETHOD = 19;
  public int JJTHASFIELD = 20;
  public int JJTTARGET = 21;
  public int JJTTHIS = 22;
  public int JJTIF = 23;
  public int JJTMETHODPATTERN = 24;
  public int JJTCONSTRUCTORPATTERN = 25;
  public int JJTFIELDPATTERN = 26;
  public int JJTPARAMETER = 27;
  public int JJTARGPARAMETER = 28;
  public int JJTATTRIBUTE = 29;
  public int JJTMODIFIER = 30;


  public String[] jjtNodeName = {
          "Root",
          "Expression",
          "void",
          "And",
          "Or",
          "Not",
          "PointcutReference",
          "Execution",
          "Call",
          "Set",
          "Get",
          "Handler",
          "Within",
          "WithinCode",
          "StaticInitialization",
          "ClassPattern",
          "Cflow",
          "CflowBelow",
          "Args",
          "HasMethod",
          "HasField",
          "Target",
          "This",
          "If",
          "MethodPattern",
          "ConstructorPattern",
          "FieldPattern",
          "Parameter",
          "ArgParameter",
          "Attribute",
          "Modifier",
  };
}
