<DOCFLEX_TEMPLATE VER='1.7'>
CREATED='2005-08-07 07:34:00'
LAST_UPDATE='2006-10-09 06:34:51'
DESIGNER_TOOL='DocFlex SDK 1.0'
TEMPLATE_TYPE='DocumentTemplate'
DSM_TYPE_ID='xsddoc'
ROOT_ETS={'xs:%complexType';'xs:%simpleType'}
<TEMPLATE_PARAMS>
	PARAM={
		param.name='fmt.allowNestedTables';
		param.displayName='Allow nested tables';
		param.type='boolean';
		param.boolean.default='true';
	}
</TEMPLATE_PARAMS>
FMT={
	doc.lengthUnits='pt';
	doc.hlink.style.link='cs6';
}
<STYLES>
	CHAR_STYLE={
		style.name='Annotation';
		style.id='cs1';
		text.font.name='Arial';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Code Smaller';
		style.id='cs2';
		text.font.name='Courier New';
		text.font.size='8';
	}
	CHAR_STYLE={
		style.name='Code Smallest';
		style.id='cs3';
		text.font.name='Courier New';
		text.font.size='7.5';
	}
	CHAR_STYLE={
		style.name='Default Paragraph Font';
		style.id='cs4';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Derivation Type';
		style.id='cs5';
		text.font.name='Verdana';
		text.font.size='8';
		text.color.foreground='#FF9900';
	}
	CHAR_STYLE={
		style.name='Hyperlink';
		style.id='cs6';
		text.decor.underline='true';
		text.color.foreground='#0000FF';
	}
	PAR_STYLE={
		style.name='Normal';
		style.id='s1';
		style.default='true';
	}
	CHAR_STYLE={
		style.name='Normal Smaller';
		style.id='cs7';
		text.font.name='Arial';
		text.font.size='9';
	}
	CHAR_STYLE={
		style.name='Normal Smallest';
		style.id='cs8';
		text.font.name='Arial';
		text.font.size='8';
	}
	PAR_STYLE={
		style.name='Properties Heading';
		style.id='s2';
		text.font.name='Arial';
		text.font.size='8';
		text.font.style.bold='true';
		text.font.style.italic='true';
		text.color.background='#CCCCFF';
		text.color.opaque='true';
		par.margin.top='6';
		par.margin.bottom='6';
		par.page.keepWithNext='true';
	}
	CHAR_STYLE={
		style.name='Property Text';
		style.id='cs9';
		text.font.name='Verdana';
		text.font.size='8';
		par.lineHeight='11';
	}
	PAR_STYLE={
		style.name='Property Title';
		style.id='s3';
		text.font.name='Arial';
		text.font.size='8';
		text.font.style.bold='true';
		par.lineHeight='11';
		par.margin.right='7';
	}
	PAR_STYLE={
		style.name='Property Value';
		style.id='s4';
		text.font.name='Verdana';
		text.font.size='8';
		par.lineHeight='11';
	}
</STYLES>
<ROOT>
	<SS_CALL>
		MATCHING_ET='xs:%simpleType'
		SS_NAME='simpleType'
	</SS_CALL>
	<FOLDER>
		DESCR='this should be a complexType with simple content only'
		MATCHING_ET='xs:%complexType'
		<BODY>
			<FOLDER>
				DESCR='switching to a restriction or an extension contained in it'
				CONTEXT_ELEMENT_EXPR='findElementByLPath("xs:simpleContent / (xs:extension | xs:restriction)")'
				MATCHING_ETS={'xs:extension%xs:simpleExtensionType';'xs:restriction%xs:simpleRestrictionType'}
				<BODY>
					<SS_CALL>
						DESCR='process the restriction'
						MATCHING_ET='xs:restriction%xs:simpleRestrictionType'
						SS_NAME='restriction'
					</SS_CALL>
					<SS_CALL>
						DESCR='process the extension'
						MATCHING_ET='xs:extension%xs:simpleExtensionType'
						SS_NAME='extension'
					</SS_CALL>
				</BODY>
			</FOLDER>
		</BODY>
	</FOLDER>
</ROOT>
<STOCK_SECTIONS>
	<FOLDER>
		MATCHING_ET='xs:%annotated'
		SS_NAME='annotation'
		<BODY>
			<TEMPLATE_CALL>
				FMT={
					txtfl.delimiter.type='space';
				}
				TEMPLATE_FILE='../misc/annotation.tpl'
				OUTPUT_TYPE='included'
				DSM_MODE='pass-current-model'
			</TEMPLATE_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ETS={'xs:%simpleExtensionType';'xs:%simpleRestrictionType';'xs:list';'xs:restriction';'xs:union'}
		SS_NAME='Derivation'
		<BODY>
			<FOLDER>
				MATCHING_ET='xs:%simpleExtensionType'
				FMT={
					text.style='cs9';
				}
				<BODY>
					<AREA_SEC>
						COND='getAttrStringValue("base") != ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='extension of'
									</LABEL>
									<DATA_CTRL>
										FMT={
											text.style='cs2';
										}
										<DOC_HLINK>
											TARGET_KEYS={
												'findElementByKey ("types", getAttrQNameValue("base")).id';
												'"detail"';
											}
										</DOC_HLINK>
										ATTR='base'
									</DATA_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='getAttrStringValue("base") == ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='extension of'
									</LABEL>
									<LABEL>
										FMT={
											text.style='cs2';
										}
										TEXT='anySimpleType'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
			<FOLDER>
				MATCHING_ETS={'xs:%simpleRestrictionType';'xs:restriction'}
				FMT={
					text.style='cs9';
				}
				<BODY>
					<AREA_SEC>
						COND='getAttrStringValue("base") != ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='restriction of'
									</LABEL>
									<DATA_CTRL>
										FMT={
											text.style='cs2';
										}
										<DOC_HLINK>
											TARGET_KEYS={
												'findElementByKey ("types", getAttrQNameValue("base")).id';
												'"detail"';
											}
										</DOC_HLINK>
										ATTR='base'
									</DATA_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='getAttrStringValue("base") == ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='restriction of'
									</LABEL>
									<LABEL>
										TEXT='embedded'
									</LABEL>
									<LABEL>
										TEXT='simpleType'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
			<FOLDER>
				MATCHING_ET='xs:list'
				FMT={
					text.style='cs9';
				}
				<BODY>
					<AREA_SEC>
						COND='getAttrStringValue("itemType") != ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='list of'
									</LABEL>
									<DATA_CTRL>
										FMT={
											text.style='cs2';
										}
										<DOC_HLINK>
											TARGET_KEYS={
												'findElementByKey ("types", getAttrQNameValue("itemType")).id';
												'"detail"';
											}
										</DOC_HLINK>
										ATTR='itemType'
									</DATA_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='getAttrStringValue("itemType") == ""'
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='list of'
									</LABEL>
									<LABEL>
										TEXT='embedded'
									</LABEL>
									<LABEL>
										TEXT='simpleType'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
			<FOLDER>
				MATCHING_ET='xs:union'
				FMT={
					txtfl.delimiter.type='text';
					txtfl.delimiter.text=' | ';
				}
				<BODY>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='space';
								}
								<CTRLS>
									<LABEL>
										FMT={
											text.style='cs5';
										}
										TEXT='by union'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
			<SS_CALL>
				FMT={
					sec.spacing.before='6';
					sec.spacing.after='6';
					text.style='cs1';
				}
				SS_NAME='annotation'
			</SS_CALL>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:%simpleExtensionType'
		SS_NAME='extension'
		<BODY>
			<FOLDER>
				FMT={
					sec.outputStyle='table';
					table.cellpadding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						FMT={
							trow.align.vert='Top';
						}
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='63';
											ctrl.size.height='17.3';
											par.style='s3';
										}
										TEXT='Derivation:'
									</LABEL>
									<SS_CALL_CTRL>
										FMT={
											ctrl.size.width='436.5';
											ctrl.size.height='17.3';
											par.style='s4';
										}
										SS_NAME='Derivation'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</BODY>
			</FOLDER>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:%facet'
		SS_NAME='Facet'
		<BODY>
			<FOLDER>
				DESCR='CASE OF ENUMERATIOM -- switch the context element back to the facets container'
				COND='instanceOf("xs:enumeration")'
				CONTEXT_ELEMENT_EXPR='iterator.contextElement'
				MATCHING_ETS={'xs:%restrictionType';'xs:restriction'}
				<BODY>
					<FOLDER>
						DESCR='if there is at least one annotation within the <xs:enumeration> elements'
						COND='findElementByLPath(\n  "xs:enumeration/xs:annotation/xs:documentation"\n) != null'
						<BODY>
							<ELEMENT_ITER>
								DESCR='if nested tables are allowed'
								COND='getBooleanParam("fmt.allowNestedTables")'
								FMT={
									sec.outputStyle='table';
									txtfl.delimiter.type='text';
									txtfl.delimiter.text=', ';
									table.cellpadding.both='0';
									table.border.style='none';
								}
								TARGET_ET='xs:enumeration'
								SCOPE='simple-location-rules'
								RULES={
									{'*','xs:enumeration'};
								}
								<BODY>
									<AREA_SEC>
										COND='findElementByLPath("xs:annotation/xs:documentation") != null'
										FMT={
											trow.align.vert='Top';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<PANEL>
														FMT={
															ctrl.size.width='79.5';
															ctrl.size.height='38.3';
															text.style='cs2';
															text.option.nbsps='true';
														}
														<AREA>
															<CTRL_GROUP>
																<CTRLS>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																	<DATA_CTRL>
																		<DOC_HLINK>
																			TARGET_KEYS={
																				'findElementByKey ("types", getAttrQNameValue("type")).id';
																				'"detail"';
																			}
																		</DOC_HLINK>
																		ATTR='value'
																	</DATA_CTRL>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																</CTRLS>
															</CTRL_GROUP>
														</AREA>
													</PANEL>
													<LABEL>
														FMT={
															ctrl.size.width='15';
															ctrl.size.height='38.3';
															tcell.option.nowrap='true';
															text.style='cs8';
															text.option.nbsps='true';
														}
														TEXT=' - '
													</LABEL>
													<SS_CALL_CTRL>
														FMT={
															ctrl.size.width='405';
															ctrl.size.height='38.3';
															text.style='cs8';
														}
														SS_NAME='annotation'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
									<AREA_SEC>
										COND='sectionBlock.execSecNone'
										FMT={
											trow.align.vert='Top';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<PANEL>
														FMT={
															ctrl.size.width='499.5';
															ctrl.size.height='38.3';
															text.style='cs2';
															text.option.nbsps='true';
														}
														<AREA>
															<CTRL_GROUP>
																<CTRLS>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																	<DATA_CTRL>
																		<DOC_HLINK>
																			TARGET_KEYS={
																				'findElementByKey ("types", getAttrQNameValue("type")).id';
																				'"detail"';
																			}
																		</DOC_HLINK>
																		ATTR='value'
																	</DATA_CTRL>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																</CTRLS>
															</CTRL_GROUP>
														</AREA>
													</PANEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</ELEMENT_ITER>
							<ELEMENT_ITER>
								DESCR='if nested tables are not allowed'
								COND='sectionBlock.execSecNone'
								TARGET_ET='xs:enumeration'
								SCOPE='simple-location-rules'
								RULES={
									{'*','xs:enumeration'};
								}
								<BODY>
									<AREA_SEC>
										FMT={
											sec.outputStyle='text-par';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<PANEL>
														FMT={
															ctrl.size.width='79.5';
															ctrl.size.height='38.3';
															text.style='cs2';
															text.option.nbsps='true';
														}
														<AREA>
															<CTRL_GROUP>
																<CTRLS>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																	<DATA_CTRL>
																		<DOC_HLINK>
																			TARGET_KEYS={
																				'findElementByKey ("types", getAttrQNameValue("type")).id';
																				'"detail"';
																			}
																		</DOC_HLINK>
																		ATTR='value'
																	</DATA_CTRL>
																	<LABEL>
																		TEXT='"'
																	</LABEL>
																</CTRLS>
															</CTRL_GROUP>
														</AREA>
													</PANEL>
													<DELIMITER>
														FMT={
															text.style='cs8';
															txtfl.delimiter.type='text';
															txtfl.delimiter.text=' - ';
														}
													</DELIMITER>
													<SS_CALL_CTRL>
														FMT={
															text.style='cs8';
														}
														SS_NAME='annotation'
													</SS_CALL_CTRL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</BODY>
							</ELEMENT_ITER>
						</BODY>
					</FOLDER>
					<ELEMENT_ITER>
						DESCR='otherwise, there are no annotations whithin <xs:enumeration> elements; print the enumeration values as a plain comma-delimited list'
						COND='sectionBlock.execSecNone'
						FMT={
							sec.outputStyle='text-par';
							text.style='cs2';
						}
						TARGET_ET='xs:enumeration'
						SCOPE='simple-location-rules'
						RULES={
							{'*','xs:enumeration'};
						}
						<BODY>
							<AREA_SEC>
								<AREA>
									<CTRL_GROUP>
										FMT={
											txtfl.delimiter.type='none';
										}
										<CTRLS>
											<LABEL>
												TEXT='"'
											</LABEL>
											<DATA_CTRL>
												<DOC_HLINK>
													TARGET_KEYS={
														'findElementByKey ("types", getAttrQNameValue("type")).id';
														'"detail"';
													}
												</DOC_HLINK>
												ATTR='value'
											</DATA_CTRL>
											<LABEL>
												TEXT='"'
											</LABEL>
											<DELIMITER>
												FMT={
													txtfl.delimiter.type='text';
													txtfl.delimiter.text=', ';
												}
											</DELIMITER>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
				</BODY>
			</FOLDER>
			<FOLDER>
				DESCR='CASE OF OTHER FACETS'
				COND='sectionBlock.execSecNone'
				<BODY>
					<AREA_SEC>
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<DATA_CTRL>
										FMT={
											text.style='cs2';
										}
										<DOC_HLINK>
											TARGET_KEYS={
												'findElementByKey ("types", getAttrQNameValue("type")).id';
												'"detail"';
											}
										</DOC_HLINK>
										ATTR='value'
									</DATA_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<TEMPLATE_CALL>
						DESCR='facet annotation'
						FMT={
							sec.spacing.before='3';
							text.style='cs8';
						}
						TEMPLATE_FILE='../misc/annotation.tpl'
						OUTPUT_TYPE='included'
						DSM_MODE='pass-current-model'
					</TEMPLATE_CALL>
				</BODY>
			</FOLDER>
		</BODY>
	</FOLDER>
	<ELEMENT_ITER>
		MATCHING_ETS={'xs:%restrictionType';'xs:restriction'}
		FMT={
			sec.outputStyle='table';
			table.cellpadding.both='0';
			table.border.style='none';
		}
		TARGET_ET='xs:%facet'
		SCOPE='simple-location-rules'
		RULES={
			{'*','xs:%facet'};
		}
		FILTER_BY_KEY='// eliminate multiple instanceof of <enumeration>\n\ninstanceOf("xs:enumeration") ? 1 : contextElement.id'
		SORTING='by-expr'
		SORTING_KEY={expr='contextElement.dsmElement.qName.localName',ascending}
		SS_NAME='Facets'
		<BODY>
			<AREA_SEC>
				FMT={
					trow.align.vert='Top';
				}
				<AREA>
					<CTRL_GROUP>
						<CTRLS>
							<DATA_CTRL>
								FMT={
									ctrl.size.width='105';
									ctrl.size.height='17.3';
									tcell.option.nowrap='true';
									par.style='s3';
								}
								FORMULA='contextElement.dsmElement.qName.localName + \':\''
							</DATA_CTRL>
							<SS_CALL_CTRL>
								FMT={
									ctrl.size.width='394.5';
									ctrl.size.height='17.3';
									tcell.align.vert='Bottom';
									tcell.padding.extra.top='1';
								}
								SS_NAME='Facet'
							</SS_CALL_CTRL>
						</CTRLS>
					</CTRL_GROUP>
				</AREA>
			</AREA_SEC>
		</BODY>
	</ELEMENT_ITER>
	<FOLDER>
		MATCHING_ETS={'xs:%simpleRestrictionType';'xs:restriction'}
		SS_NAME='restriction'
		<BODY>
			<FOLDER>
				FMT={
					sec.outputStyle='table';
					table.cellpadding.both='0';
					table.border.style='none';
				}
				<BODY>
					<AREA_SEC>
						FMT={
							trow.align.vert='Top';
						}
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='63';
											ctrl.size.height='17.3';
											par.style='s3';
										}
										TEXT='Derivation:'
									</LABEL>
									<SS_CALL_CTRL>
										FMT={
											ctrl.size.width='436.5';
											ctrl.size.height='17.3';
											par.style='s4';
										}
										SS_NAME='Derivation'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<AREA_SEC>
						COND='getBooleanParam("fmt.allowNestedTables") && hasChild("xs:%facet")'
						FMT={
							trow.align.vert='Top';
						}
						<AREA>
							<CTRL_GROUP>
								<CTRLS>
									<LABEL>
										FMT={
											ctrl.size.width='63';
											ctrl.size.height='17.3';
											par.style='s3';
											par.lineHeight='13';
										}
										TEXT='Facets:'
									</LABEL>
									<SS_CALL_CTRL>
										FMT={
											ctrl.size.width='436.5';
											ctrl.size.height='17.3';
											tcell.padding.extra.top='1';
										}
										SS_NAME='Facets'
									</SS_CALL_CTRL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
					<ELEMENT_ITER>
						DESCR='in the case nested tables are not allowed'
						COND='! getBooleanParam("fmt.allowNestedTables")'
						TARGET_ET='xs:%facet'
						SCOPE='simple-location-rules'
						RULES={
							{'*','xs:%facet'};
						}
						FILTER_BY_KEY='// eliminate multiple instanceof of <enumeration>\n\ninstanceOf("xs:enumeration") ? 1 : contextElement.id'
						SORTING='by-expr'
						SORTING_KEY={expr='contextElement.dsmElement.qName.localName',ascending}
						<BODY>
							<AREA_SEC>
								COND='iterator.isFirstItem'
								FMT={
									trow.align.vert='Top';
								}
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='63';
													ctrl.size.height='17.3';
													par.style='s3';
												}
												TEXT='Facets:'
											</LABEL>
											<DATA_CTRL>
												FMT={
													ctrl.size.width='72';
													ctrl.size.height='17.3';
													tcell.option.nowrap='true';
													par.style='s3';
												}
												FORMULA='contextElement.dsmElement.qName.localName + \':\''
											</DATA_CTRL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='364.5';
													ctrl.size.height='17.3';
													tcell.align.vert='Bottom';
													tcell.padding.extra.top='1';
												}
												SS_NAME='Facet'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<AREA_SEC>
								COND='! iterator.isFirstItem'
								FMT={
									trow.align.vert='Top';
								}
								<AREA>
									<CTRL_GROUP>
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='63';
													ctrl.size.height='17.3';
													par.style='s3';
												}
												TEXT=''
											</LABEL>
											<DATA_CTRL>
												FMT={
													ctrl.size.width='72';
													ctrl.size.height='17.3';
													tcell.option.nowrap='true';
													par.style='s3';
												}
												FORMULA='contextElement.dsmElement.qName.localName + \':\''
											</DATA_CTRL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='364.5';
													ctrl.size.height='17.3';
													tcell.align.vert='Bottom';
													tcell.padding.extra.top='1';
												}
												SS_NAME='Facet'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
						</BODY>
					</ELEMENT_ITER>
				</BODY>
			</FOLDER>
			<FOLDER>
				DESCR='embedded simpleType definition'
				COND='getAttrStringValue("base") == ""'
				<BODY>
					<SS_CALL>
						FMT={
							sec.spacing.after='6';
							text.style='cs1';
						}
						SS_NAME='annotation'
					</SS_CALL>
					<SS_CALL>
						FMT={
							sec.indent.block='true';
						}
						SS_NAME='simpleType'
						PASSED_ELEMENT_EXPR='findChild("xs:simpleType")'
						PASSED_ELEMENT_MATCHING_ET='xs:%localSimpleType'
					</SS_CALL>
				</BODY>
				<HEADER>
					<AREA_SEC>
						FMT={
							par.style='s2';
						}
						<AREA>
							<CTRL_GROUP>
								FMT={
									txtfl.delimiter.type='none';
								}
								<CTRLS>
									<LABEL>
										TEXT='Embedded Type'
									</LABEL>
								</CTRLS>
							</CTRL_GROUP>
						</AREA>
					</AREA_SEC>
				</HEADER>
			</FOLDER>
		</BODY>
	</FOLDER>
	<FOLDER>
		MATCHING_ET='xs:%simpleType'
		SS_NAME='simpleType'
		<BODY>
			<ELEMENT_ITER>
				FMT={
					txtfl.delimiter.type='space';
				}
				TARGET_ETS={'xs:list';'xs:restriction';'xs:union'}
				SCOPE='simple-location-rules'
				RULES={
					{'*','(xs:list|xs:restriction|xs:union)'};
				}
				<BODY>
					<SS_CALL>
						SS_NAME='restriction'
					</SS_CALL>
					<FOLDER>
						MATCHING_ET='xs:list'
						<BODY>
							<AREA_SEC>
								FMT={
									sec.outputStyle='table';
									table.cellpadding.both='0';
									table.border.style='none';
									trow.align.vert='Top';
								}
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='63';
													ctrl.size.height='17.3';
													par.style='s3';
												}
												TEXT='Derivation:'
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='436.5';
													ctrl.size.height='17.3';
													par.style='s4';
												}
												SS_NAME='Derivation'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<FOLDER>
								DESCR='embedded type definition'
								COND='getAttrStringValue("itemType") == ""'
								<BODY>
									<SS_CALL>
										FMT={
											sec.spacing.after='6';
											text.style='cs1';
										}
										SS_NAME='annotation'
									</SS_CALL>
									<SS_CALL>
										FMT={
											sec.indent.block='true';
										}
										SS_NAME='simpleType'
										PASSED_ELEMENT_EXPR='findChild("xs:simpleType")'
										PASSED_ELEMENT_MATCHING_ET='xs:%localSimpleType'
									</SS_CALL>
								</BODY>
								<HEADER>
									<AREA_SEC>
										FMT={
											par.style='s2';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														TEXT='Embedded Type'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</HEADER>
							</FOLDER>
						</BODY>
					</FOLDER>
					<FOLDER>
						MATCHING_ET='xs:union'
						<BODY>
							<AREA_SEC>
								FMT={
									sec.outputStyle='table';
									table.cellpadding.both='0';
									table.border.style='none';
									trow.align.vert='Top';
								}
								<AREA>
									<CTRL_GROUP>
										FMT={
											trow.align.vert='Top';
										}
										<CTRLS>
											<LABEL>
												FMT={
													ctrl.size.width='63';
													ctrl.size.height='17.3';
													par.style='s3';
												}
												TEXT='Derivation:'
											</LABEL>
											<SS_CALL_CTRL>
												FMT={
													ctrl.size.width='436.5';
													ctrl.size.height='17.3';
													par.style='s4';
												}
												SS_NAME='Derivation'
											</SS_CALL_CTRL>
										</CTRLS>
									</CTRL_GROUP>
								</AREA>
							</AREA_SEC>
							<FOLDER>
								DESCR='member types'
								FMT={
									sec.outputStyle='list';
									text.style='cs9';
									list.type='ordered';
								}
								<BODY>
									<ATTR_ITER>
										DESCR='global member types'
										FMT={
											sec.outputStyle='list-items';
											txtfl.delimiter.type='text';
											txtfl.delimiter.text=', ';
										}
										SCOPE='attr-values'
										ATTR='memberTypes'
										<BODY>
											<AREA_SEC>
												<AREA>
													<CTRL_GROUP>
														<CTRLS>
															<DATA_CTRL>
																FMT={
																	text.style='cs2';
																}
																<DOC_HLINK>
																	TARGET_KEYS={
																		'findElementByKey ("types", toQName (iterator.value)).id';
																		'"detail"';
																	}
																</DOC_HLINK>
																FORMULA='iterator.value'
															</DATA_CTRL>
														</CTRLS>
													</CTRL_GROUP>
												</AREA>
											</AREA_SEC>
										</BODY>
									</ATTR_ITER>
									<ELEMENT_ITER>
										DESCR='embedded member types'
										FMT={
											sec.outputStyle='list-items';
											li.margin.top='6';
											li.margin.bottom='6';
										}
										TARGET_ET='xs:%localSimpleType'
										SCOPE='simple-location-rules'
										RULES={
											{'*','xs:%localSimpleType'};
										}
										<BODY>
											<FOLDER>
												DESCR='this in the case there annotation to the member type; otherwise, print its derivation detail directly'
												<BODY>
													<AREA_SEC>
														<AREA>
															<CTRL_GROUP>
																FMT={
																	par.margin.bottom='6';
																}
																<CTRLS>
																	<LABEL>
																		TEXT='embedded simpleType:'
																	</LABEL>
																</CTRLS>
															</CTRL_GROUP>
														</AREA>
													</AREA_SEC>
													<SS_CALL>
														FMT={
															sec.spacing.after='6';
															text.style='cs1';
														}
														SS_NAME='annotation'
													</SS_CALL>
													<SS_CALL>
														SS_NAME='simpleType'
													</SS_CALL>
												</BODY>
											</FOLDER>
										</BODY>
									</ELEMENT_ITER>
								</BODY>
								<HEADER>
									<AREA_SEC>
										FMT={
											par.style='s2';
										}
										<AREA>
											<CTRL_GROUP>
												FMT={
													txtfl.delimiter.type='none';
												}
												<CTRLS>
													<LABEL>
														TEXT='Member Types'
													</LABEL>
												</CTRLS>
											</CTRL_GROUP>
										</AREA>
									</AREA_SEC>
								</HEADER>
							</FOLDER>
						</BODY>
					</FOLDER>
				</BODY>
			</ELEMENT_ITER>
		</BODY>
	</FOLDER>
</STOCK_SECTIONS>
CHECKSUM='HtxSCRCQhozfhns7AKsDdg'
</DOCFLEX_TEMPLATE>