/*
 * All content copyright Terracotta, Inc., unless otherwise indicated. All rights reserved.
 */

/* Generated By:JJTree: Do not edit this line. ASTAttribute.java */
package com.tc.aspectwerkz.expression.ast;

public class ASTAttribute extends SimpleNode {
  private String m_name;

  private boolean m_not = false;

  public ASTAttribute(int id) {
    super(id);
  }

  public ASTAttribute(ExpressionParser p, int id) {
    super(p, id);
  }

  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setName(String name) {
    // remove the first '@'
    m_name = name.substring(1, name.length());
  }

  public String getName() {
    return m_name;
  }

  public void toggleNot() {
    m_not = !m_not;
  }

  public boolean isNot() {
    return m_not;
  }
}
