/*
 * All content copyright Terracotta, Inc., unless otherwise indicated. All rights reserved.
 */

/* Generated By:JJTree: Do not edit this line. ASTModifier.java */
package com.tc.aspectwerkz.expression.ast;

public class ASTModifier extends SimpleNode {
  private int m_modifier;

  private boolean m_not = false;

  public ASTModifier(int id) {
    super(id);
  }

  public ASTModifier(ExpressionParser p, int id) {
    super(p, id);
  }

  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void toggleNot() {
    m_not = !m_not;
  }

  public boolean isNot() {
    return m_not;
  }

  public void setModifier(int modifier) {
    m_modifier = modifier;
  }

  public int getModifier() {
    return m_modifier;
  }
}
