/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_tc_util_runtime_GetPid */

#ifndef _Included_com_tc_util_runtime_GetPid
#define _Included_com_tc_util_runtime_GetPid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tc_util_runtime_GetPid
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tc_util_runtime_GetPid_getPid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
